name: run-tests
on: [ push ]
jobs:
  run-maven-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - run: mvn --batch-mode clean verify -U
